# Generated by Django 5.1.3 on 2024-11-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Random',
        ),
    ]
