# Generated by Django 5.1.2 on 2024-11-29 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_company_job_appliedjob_pinnedjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="default", max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.company",
            ),
        ),
    ]
