# Generated by Django 5.1.2 on 2024-12-06 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_post_options_post_created_post_updated"),
        ("base", "0004_alter_job_appliedstatus_alter_job_numberofapplicants"),
    ]

    operations = []
